export const CLASS_LABELS = {
  0: "exact",
  1: "digit",
  2: "lower",
  3: "upper",
  4: "alpha",
  5: "alnum",
  6: "hex",
  7: "base64",
  8: "any",
};

export const REGISTRY = {
  patterns: {
    "in.aadhar": {
      name: "Aadhar Number",
      desc: "12-digit Indian identity number",
      industry: ["india_kyc", "banking", "healthcare", "fintech"],
      regulation: "Aadhar Act 2016",
      types: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      len: 12,
      example: "234567890123",
    },
    "in.pan": {
      name: "PAN Card",
      desc: "Indian PAN format AAAAA0000A",
      industry: ["india_kyc", "banking", "fintech"],
      regulation: "Income Tax Act",
      types: [3, 3, 3, 3, 3, 1, 1, 1, 1, 3],
      len: 10,
      example: "ABCDE1234F",
    },
    "in.passport": {
      name: "Indian Passport",
      desc: "Letter followed by seven digits",
      industry: ["india_kyc"],
      regulation: "Passport Act",
      types: [3, 1, 1, 1, 1, 1, 1, 1],
      len: 8,
      example: "A1234567",
    },
    "in.voter": {
      name: "Indian Voter ID",
      desc: "Three letters followed by seven digits",
      industry: ["india_kyc"],
      regulation: "RPA 1950",
      types: [3, 3, 3, 1, 1, 1, 1, 1, 1, 1],
      len: 10,
      example: "ABC1234567",
    },
    "pii.ssn": {
      name: "US SSN",
      desc: "Social Security Number",
      industry: ["banking", "healthcare", "insurance"],
      regulation: "Privacy Act",
      types: [1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
      values: [0, 0, 0, 45, 0, 0, 45, 0, 0, 0, 0],
      len: 11,
      example: "123-45-6789",
    },
    "pii.phone_in": {
      name: "Indian Phone",
      desc: "+91 followed by 10 digits",
      industry: ["india_kyc", "telecom"],
      regulation: "TRAI",
      types: [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      values: [43, 57, 49],
      len: 13,
      example: "+919876543210",
    },
    "pii.dob_iso": {
      name: "Date of Birth",
      desc: "YYYY-MM-DD format",
      industry: ["healthcare", "banking", "insurance"],
      regulation: "GDPR / CCPA",
      types: [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
      values: [0, 0, 0, 0, 45, 0, 0, 45, 0, 0],
      len: 10,
      example: "1990-01-15",
    },
    "fin.cc16": {
      name: "Credit Card",
      desc: "16-digit payment card number",
      industry: ["banking", "fintech", "ecommerce"],
      regulation: "PCI DSS",
      types: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      len: 16,
      example: "4111111111111111",
    },
    "fin.routing": {
      name: "US Routing Number",
      desc: "9-digit ABA routing number",
      industry: ["banking", "fintech"],
      regulation: "Federal Reserve",
      types: [1, 1, 1, 1, 1, 1, 1, 1, 1],
      len: 9,
      example: "021000021",
    },
    "health.npi": {
      name: "NPI",
      desc: "10-digit provider identifier",
      industry: ["healthcare"],
      regulation: "HIPAA",
      types: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      len: 10,
      example: "1234567890",
    },
    "health.dea": {
      name: "DEA Number",
      desc: "Two letters followed by seven digits",
      industry: ["healthcare"],
      regulation: "DEA CSA",
      types: [3, 3, 1, 1, 1, 1, 1, 1, 1],
      len: 9,
      example: "AB1234567",
    },
    "tech.aws_key": {
      name: "AWS Access Key",
      desc: "AKIA followed by 16 alphanumeric chars",
      industry: ["saas", "devops", "cloud"],
      regulation: "SOC 2",
      types: [0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      values: [65, 75, 73, 65],
      len: 20,
      example: "AKIAIOSFODNN7EXAMPLE",
    },
    "tech.github_pat": {
      name: "GitHub PAT",
      desc: "ghp_ token prefix and alphanumeric body",
      industry: ["saas", "devops"],
      regulation: "SOC 2",
      types: [0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      values: [103, 104, 112, 95],
      len: 32,
      example: "ghp_ABCDEFGHIJABCDEFGHIJABCDE",
    },
    "tech.openai_key": {
      name: "OpenAI API Key",
      desc: "sk- prefix followed by alphanumeric body",
      industry: ["saas", "ai"],
      regulation: "SOC 2",
      types: [0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      values: [115, 107, 45],
      len: 23,
      example: "sk-abc123abc123abc123ab",
    },
    "tech.stripe_key": {
      name: "Stripe Secret Key",
      desc: "sk_live_ prefix and 24 alphanumeric chars",
      industry: ["fintech", "ecommerce", "saas"],
      regulation: "PCI DSS",
      types: [0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      values: [115, 107, 95, 108, 105, 118, 101, 95],
      len: 32,
      example: "sk_live_ABCDEFGHIJKLMNOPQRSTUVWX",
    },
  },
  presets: {
    india_kyc: {
      name: "India KYC",
      short: "KYC",
      accent: "#276ef1",
      patterns: ["in.aadhar", "in.pan", "in.passport", "in.voter", "pii.phone_in"],
    },
    banking: {
      name: "Banking",
      short: "Bank",
      accent: "#00875a",
      patterns: ["in.aadhar", "pii.ssn", "fin.cc16", "fin.routing", "pii.dob_iso"],
    },
    healthcare: {
      name: "Healthcare",
      short: "Health",
      accent: "#c2410c",
      patterns: ["pii.ssn", "health.npi", "health.dea", "pii.dob_iso", "in.aadhar"],
    },
    fintech: {
      name: "Fintech",
      short: "Fin",
      accent: "#7c3aed",
      patterns: ["fin.cc16", "in.aadhar", "in.pan", "tech.stripe_key", "pii.ssn"],
    },
    saas: {
      name: "SaaS / DevOps",
      short: "SaaS",
      accent: "#0f766e",
      patterns: ["tech.aws_key", "tech.github_pat", "tech.openai_key", "tech.stripe_key"],
    },
  },
};
