/**
 * Compute → Circuit bridge.
 *
 * Reads a samples/inference-*.log.json (mock or real — same shape), then:
 *   1. extracts the prompt and a sensitive target field
 *   2. zero-pads to the circuit's fixed sizes (prompt=512, target=32 bytes)
 *   3. computes Poseidon2 sponge hashes that match the Noir circuit's
 *      poseidon2_hash_512 / poseidon2_hash_32 (verified by self-test below)
 *   4. writes Circuit/ghostprover/Prover.toml with all witnesses + public
 *      inputs so `nargo execute` / `nargo prove` runs unchanged
 *   5. cross-checks `commitment` against the TEE-attested request_hash
 *      shape in `zerogAuth.parsed` (sanity log only — the actual binding
 *      lives on-chain in Phase 2's GhostProverRegistry.submitReceipt)
 *
 * Self-test: on every run we re-hash the medical-prompt fixture from
 * `test_print_prover_hashes` and assert it equals the value Noir produced
 * (0x2a7c9afe...). Catches breakage if the sponge IV / round constants ever
 * drift between this JS lib and Noir stdlib.
 *
 * Usage:
 *   npm run bridge -- --target "234567890123"
 *   npm run bridge -- --target "234567890123" --sample samples/inference-XYZ.log.json
 */
import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { poseidon2Hash } from '@zkpassport/poseidon2';

const PROMPT_MAX = 512;
const TARGET_MAX = 32;

// Known good hash from `nargo test --show-output test_print_prover_hashes`
// over the medical prompt fixture in Circuit/ghostprover/src/main.nr.
const SELF_TEST_COMMITMENT =
  '0x2a7c9afe09311823202d1411a5b006b9ce935937416bfa7d648905c3b7a0b884';
const SELF_TEST_PROMPT =
  'What are the treatment options for a patient with high blood pressure and diabetes?';

// ---------------------------------------------------------------------------
// Padding + hashing
// ---------------------------------------------------------------------------

function padBytes(s: string, len: number): { bytes: number[]; actualLen: number } {
  const raw = Buffer.from(s, 'utf8');
  if (raw.length > len) {
    throw new Error(`Input ${raw.length} bytes exceeds circuit max ${len}`);
  }
  const bytes = new Array<number>(len).fill(0);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw[i];
  return { bytes, actualLen: raw.length };
}

function hashBytes(bytes: number[]): bigint {
  // Mirrors `prompt_bytes.map(|b| b as Field)` in main.nr.
  const fields = bytes.map((b) => BigInt(b));
  return poseidon2Hash(fields);
}

function toHex32(b: bigint): string {
  return '0x' + b.toString(16).padStart(64, '0');
}

// ---------------------------------------------------------------------------
// Self-test — fail fast if JS poseidon2 stops matching Noir stdlib.
// ---------------------------------------------------------------------------

function selfTest() {
  const { bytes } = padBytes(SELF_TEST_PROMPT, PROMPT_MAX);
  const got = toHex32(hashBytes(bytes));
  if (got.toLowerCase() !== SELF_TEST_COMMITMENT.toLowerCase()) {
    throw new Error(
      `[bridge] poseidon2 self-test FAILED.\n` +
        `  expected ${SELF_TEST_COMMITMENT}\n` +
        `  got      ${got}\n` +
        `This means @zkpassport/poseidon2 no longer matches Noir's stdlib ` +
        `poseidon2 sponge construction. Do NOT trust generated Prover.toml.`,
    );
  }
  console.log('[bridge] poseidon2 self-test OK');
}

// ---------------------------------------------------------------------------
// Prover.toml writer
// ---------------------------------------------------------------------------

function tomlByteArray(name: string, bytes: number[]): string {
  const lines = [`${name} = [`];
  for (const b of bytes) lines.push(`    ${b},`);
  lines.push(']');
  return lines.join('\n');
}

interface ProverInputs {
  prompt: string;
  target: string;
  commitment: string;
  targetHash: string;
  source: string; // inference log path (or 'inline')
  zerogAuthRequestHash?: string | null;
}

function renderProverToml(inputs: ProverInputs): string {
  const prompt = padBytes(inputs.prompt, PROMPT_MAX);
  const target = padBytes(inputs.target, TARGET_MAX);
  return [
    '# GhostProver - Prover.toml (auto-generated by Compute/src/bridge.ts)',
    '# DO NOT EDIT MANUALLY — re-run `npm run bridge` to regenerate.',
    '#',
    `# Source inference log : ${inputs.source}`,
    `# Prompt               : ${JSON.stringify(inputs.prompt)}`,
    `# Target (sensitive)   : ${JSON.stringify(inputs.target)}`,
    `# TEE request_hash     : ${inputs.zerogAuthRequestHash ?? '(none — log had no zerogAuth)'}`,
    '',
    '# --- Private inputs ---',
    '',
    tomlByteArray('prompt_bytes', prompt.bytes),
    '',
    tomlByteArray('target_bytes', target.bytes),
    '',
    `target_len = ${target.actualLen}`,
    `prompt_len = ${prompt.actualLen}`,
    '',
    '# --- Public inputs ---',
    '',
    `commitment = "${inputs.commitment}"`,
    `target_hash = "${inputs.targetHash}"`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(argv: string[]) {
  const out: { target?: string; sample?: string; prompt?: string } = {};
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    const v = argv[i + 1];
    if (k === '--target') { out.target = v; i++; }
    else if (k === '--sample') { out.sample = v; i++; }
    else if (k === '--prompt') { out.prompt = v; i++; }
  }
  return out;
}

function findLatestSample(): string | null {
  const dir = path.resolve('samples');
  if (!fs.existsSync(dir)) return null;
  const candidates = fs.readdirSync(dir)
    .filter((f) => f.startsWith('inference-') && f.endsWith('.log.json'))
    .map((f) => ({ f, full: path.join(dir, f), mtime: fs.statSync(path.join(dir, f)).mtimeMs }))
    .sort((a, b) => b.mtime - a.mtime);
  return candidates[0]?.full ?? null;
}

function main() {
  selfTest();

  const args = parseArgs(process.argv.slice(2));
  if (!args.target) {
    throw new Error(
      'Missing --target "<sensitive field>". This is the substring the ZK proof will ' +
      'attest is ABSENT from the prompt. Example: --target "234567890123"',
    );
  }

  let prompt = args.prompt;
  let source = 'inline (no --sample)';
  let zerogAuthRequestHash: string | null = null;

  if (!prompt) {
    const samplePath = args.sample ?? findLatestSample();
    if (!samplePath) {
      throw new Error(
        'No prompt provided and no inference log found. Run `npm run inference:mock` first ' +
        'or pass --prompt "<text>".',
      );
    }
    const log = JSON.parse(fs.readFileSync(samplePath, 'utf8'));
    prompt = log?.prompt;
    if (typeof prompt !== 'string') {
      throw new Error(`Inference log ${samplePath} has no top-level .prompt string`);
    }
    source = path.relative(process.cwd(), samplePath);
    zerogAuthRequestHash = log?.zerogAuth?.parsed?.request_hash ?? null;
    console.log(`[bridge] loaded prompt from ${source}`);
  }

  const { bytes: promptBytes } = padBytes(prompt, PROMPT_MAX);
  const { bytes: targetBytes } = padBytes(args.target, TARGET_MAX);
  const commitment = toHex32(hashBytes(promptBytes));
  const targetHash = toHex32(hashBytes(targetBytes));

  console.log(`[bridge] commitment  = ${commitment}`);
  console.log(`[bridge] target_hash = ${targetHash}`);

  // Sanity: warn (don't fail) if the TEE-attested request_hash doesn't
  // match our commitment. They are *different by construction*
  // (request_hash = sha256 of the chat-completion body, commitment =
  // poseidon2 of raw prompt bytes), but Phase 2's on-chain verifier
  // will need to bind one to the other.
  if (zerogAuthRequestHash) {
    console.log(`[bridge] note: zerogAuth.request_hash = ${zerogAuthRequestHash}`);
    console.log('[bridge] note: this is sha256(body) per 0G spec, NOT poseidon2(prompt).');
    console.log('[bridge] note: Phase 2 receipt binds both into the audit bundle.');
  }

  const toml = renderProverToml({
    prompt,
    target: args.target,
    commitment,
    targetHash,
    source,
    zerogAuthRequestHash,
  });

  const proverPath = path.resolve('..', 'Circuit', 'ghostprover', 'Prover.toml');
  fs.writeFileSync(proverPath, toml);
  console.log(`[bridge] wrote ${proverPath}`);
}

main();
